### ISSUE TITLE
Feature request: await

### ISSUE THREAD

**Issue by Juerd** [ryn1x/Terminal-Spinners#1]
It would be nice if Terminal::Spinners had an `await` method, so you can just replace `await` with `$spinner.await: ` and get a nice spinner. Or maybe even write an Awaiter, so `$*AWAITER = Spinner::Awaiter.new(...)` makes every subsequent `await` get a spinner.

**Comment by ryn1x** [comment]
I think this is a great idea. I will work on it if I get time, or am happy to merge a pull request if someone else wants to add the feature.

**Comment by ryn1x** [comment]
Done and uploaded to CPAN. Enjoy!
